-- Schéma
DROP SCHEMA IF EXISTS quizzbus CASCADE;
CREATE SCHEMA quizzbus;

-- Tables
CREATE TABLE compte (
    idcompte INT GENERATED BY DEFAULT AS IDENTITY,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    date_naissance DATE NOT NULL,
    motdepasse VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    flagAdmin BOOLEAN NOT NULL,
    ville VARCHAR(100) NOT NULL,
    categorie VARCHAR(100) NOT NULL,
    UNIQUE(nom),
    PRIMARY KEY(idcompte)
);

CREATE TABLE Resultat (
    idresultat INT GENERATED BY DEFAULT AS IDENTITY,
    heure TIME NOT NULL,
    score INTEGER NOT NULL,
    PRIMARY KEY(idresultat)
);

CREATE TABLE Poste (
    idposte INT GENERATED BY DEFAULT AS IDENTITY,
    libelle VARCHAR(200) NOT NULL,
    PRIMARY KEY(idposte)
);

CREATE TABLE Theme (
    idtheme INT GENERATED BY DEFAULT AS IDENTITY,
    nom VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    PRIMARY KEY(idtheme)
);

CREATE TABLE Quiz (
    idquizz INT GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(200) NOT NULL,
    idtheme INTEGER NOT NULL,
    PRIMARY KEY(idquizz),
    FOREIGN KEY(idtheme) REFERENCES Theme(idtheme)
);

CREATE TABLE Question (
    idquestion INT GENERATED BY DEFAULT AS IDENTITY,
    enonce VARCHAR(200) NOT NULL,
    idquizz INTEGER,
    astuce VARCHAR(200),
    reponse1 VARCHAR(200) NOT NULL,
    reponse2 VARCHAR(200) NOT NULL,
    reponse3 VARCHAR(200) NOT NULL,
    reponse4 VARCHAR(200) NOT NULL,
    reponse INTEGER,
    PRIMARY KEY(idquestion),
    FOREIGN KEY(idquizz) REFERENCES Quiz(idquizz)
);

CREATE TABLE Media (
    idmedia INT GENERATED BY DEFAULT AS IDENTITY,
    titre VARCHAR(50) NOT NULL,
    description VARCHAR(50) NOT NULL,
    PRIMARY KEY(idmedia)
);

CREATE TABLE Joueur (
    idjoueur INT GENERATED BY DEFAULT AS IDENTITY,
    ville VARCHAR(50) NOT NULL,
    categorie VARCHAR(50) NOT NULL,
    idposte INTEGER NOT NULL,
    PRIMARY KEY(idjoueur),
    FOREIGN KEY(idposte) REFERENCES Poste(idposte)
);

CREATE TABLE Parcours (
    idparcours INT GENERATED BY DEFAULT AS IDENTITY,
    mode VARCHAR(50) NOT NULL,
    PRIMARY KEY(idparcours)
);

CREATE TABLE Statistique (
    idstat INT GENERATED BY DEFAULT AS IDENTITY,
    libelle VARCHAR(50) NOT NULL,
    PRIMARY KEY(idstat)
);

CREATE TABLE Configuration_Poste (
    idconf INT GENERATED BY DEFAULT AS IDENTITY,
    heure TIME,
    idparcours INTEGER NOT NULL,
    idtheme INTEGER NOT NULL,
    score INTEGER NOT NULL,
    question INTEGER NOT NULL,
    PRIMARY KEY(idconf),
    FOREIGN KEY(idparcours) REFERENCES Parcours(idparcours),
    FOREIGN KEY(idtheme) REFERENCES Theme(idtheme)
);

CREATE TABLE Reponse (
    idreponse INT GENERATED BY DEFAULT AS IDENTITY,
    libelle VARCHAR(100) NOT NULL,
    PRIMARY KEY(idreponse)
);

CREATE TABLE avoir (
    idquestion INTEGER,
    idtheme INTEGER,
    PRIMARY KEY(idquestion, idtheme),
    FOREIGN KEY(idquestion) REFERENCES Question(idquestion),
    FOREIGN KEY(idtheme) REFERENCES Theme(idtheme)
);

CREATE TABLE administrer (
    idcompte INTEGER,
    idposte INTEGER,
    PRIMARY KEY(idcompte, idposte),
    FOREIGN KEY(idcompte) REFERENCES compte(idcompte),
    FOREIGN KEY(idposte) REFERENCES Poste(idposte)
);

CREATE TABLE elaborer (
    idcompte INTEGER,
    idconf INTEGER,
    PRIMARY KEY(idcompte, idconf),
    FOREIGN KEY(idcompte) REFERENCES compte(idcompte),
    FOREIGN KEY(idconf) REFERENCES Configuration_Poste(idconf)
);

CREATE TABLE posseder (
    idquizz INTEGER,
    idresultat INTEGER,
    PRIMARY KEY(idquizz, idresultat),
    FOREIGN KEY(idquizz) REFERENCES Quiz(idquizz),
    FOREIGN KEY(idresultat) REFERENCES Resultat(idresultat)
);

CREATE TABLE contenir (
    idquizz INTEGER,
    idquestion INTEGER,
    PRIMARY KEY(idquizz, idquestion),
    FOREIGN KEY(idquizz) REFERENCES Quiz(idquizz),
    FOREIGN KEY(idquestion) REFERENCES Question(idquestion)
);

CREATE TABLE inclure (
    idquestion INTEGER,
    idmedia INTEGER,
    PRIMARY KEY(idquestion, idmedia),
    FOREIGN KEY(idquestion) REFERENCES Question(idquestion),
    FOREIGN KEY(idmedia) REFERENCES Media(idmedia)
);

CREATE TABLE effectuer (
    idquizz INTEGER,
    idjoueur INTEGER,
    PRIMARY KEY(idquizz, idjoueur),
    FOREIGN KEY(idquizz) REFERENCES Quiz(idquizz),
    FOREIGN KEY(idjoueur) REFERENCES Joueur(idjoueur)
);

CREATE TABLE etre_affilier_à (
    idquizz INTEGER,
    idparcours INTEGER,
    PRIMARY KEY(idquizz, idparcours),
    FOREIGN KEY(idquizz) REFERENCES Quiz(idquizz),
    FOREIGN KEY(idparcours) REFERENCES Parcours(idparcours)
);

CREATE TABLE consulter (
    idcompte INTEGER,
    idstat INTEGER,
    PRIMARY KEY(idcompte, idstat),
    FOREIGN KEY(idcompte) REFERENCES compte(idcompte),
    FOREIGN KEY(idstat) REFERENCES Statistique(idstat)
);

CREATE TABLE generer (
    idresultat INTEGER,
    idstat INTEGER,
    PRIMARY KEY(idresultat, idstat),
    FOREIGN KEY(idresultat) REFERENCES Resultat(idresultat),
    FOREIGN KEY(idstat) REFERENCES Statistique(idstat)
);
